--- #YAML:1.0
name:               Test-Device-SerialPort
version:            0.05
abstract:           Serial port mock object to be used for testing
author:
    - Cosimo Streppone <cosimo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
resources:
    bugtracker:  mailto:bug-test-device-serialport@rt.cpan.org
    license:     http://dev.perl.org/licenses/
    repository:  git://github.com/cosimo/perl5-test-device-serialport.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
